USE [CMSPlus]
GO

CREATE TABLE Comments(
	Id INT Identity(1,1) PRIMARY KEY,
	TopicId INT NOT NULL,
	FullName NVARCHAR(256) NOT NULL,
	CommentText NVARCHAR(1000) NOT NULL,
	CreatedOnUtc DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_Comments_Posts FOREIGN KEY (TopicId) REFERENCES Topics(Id)
);
GO
